# Server Configuration
server:
  port: 8086
  servlet:
    context-path: /api/v1/
# Spring Configuration
spring:
  application:
    name: ms-bill
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/e-commerce
            provider-uri: http://localhost:8081/
        registration:
          keycloak:
            client-name: keycloak
            realm: e-commerce
            clientId: ms-bills-client
            clientSecret: secret
            scope: openid
            redirect-uri: http://localhost:8086/login/oauth2/code/keycloak
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=10
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false
  # H2
h2:
  console:
    enabled: true
    path: /h2-console
  # Eureka Configuration
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

